version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      # Install project dependencies
      - npm install

  build:
    commands:
      # Build the React application for production
      - npm run build # Corrected to "build" instead of "prod"

  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/reactjs-sample/ s3://test-react-soft --delete









